<?php $now = new DateTime(); ?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app">
    <title><?php echo $this->title ?></title>
    <link rel="self" href="<?php echo $this->selfLink ?>" />
    <updated><?php echo $now->format('Y-m-d\TH:i:s\Z')  ?></updated>
    <generator uri="<?php echo $this->selfLink ?>">
        <?php echo $this->title ?>
    </generator>
    <id><?php echo $this->apiEndPoint ?>/datapoints</id>

    <?php
    if (isset($this->items)):
        foreach ($this->items as $item): /* @var $item SE\Entity\TrackingItem */
    ?>

            <entry>
                <title>Data Point For: <?php echo ucfirst($item->getTerm()->getTerm()) ?></title>
                <id><?php echo $this->selfLink ?>/id/<?php echo $item->getId() ?></id>
                <updated><?php echo $item->getDateTime()->format('Y-m-d\TH:i:s\Z'); ?></updated>
                <app:edited><?php echo $item->getDateTime()->format('Y-m-d\TH:i:s\Z') ?></app:edited>
                <author>
                    <name>USER</name>
                </author>
                <content type="application/vnd.resbucks+xml">
                    <datapoint>
                        <datetime><?php echo $item->getDateTime()->format('Y-m-d H:i:s'); ?></datetime>
                        <sample><?php echo $item->getSampled(); ?></sample>
                        <positive><?php echo $item->getPositive();  ?></positive>
                        <negative><?php echo $item->getNegative(); ?></negative>
                        <unclassified><?php echo $item->getUnclassified(); ?></unclassified>
                    </datapoint>
                </content>

            <link rel="self" href="<?php echo $this->selfLink . '/id/'. $item->getId() ?>" />
            <link rel="term" href="<?php echo $this->apiEndPoint .'/tracking/id/'. $item->getTerm()->getId() ?>" />
            </entry>

    <?php
                endforeach;
            endif;
    ?>

</feed>


