<?php $now = new DateTime(); ?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app">
    <title><?php echo $this->title ?></title>
    <link rel="self" href="<?php echo $this->apiEndPoint ?>/tracking" />
    <updated><?php echo $now->format('Y-m-d\TH:i:s\Z')  ?></updated>
    <generator uri="<?php echo $this->apiEndPoint ?>/tracking">
        <?php echo $this->title ?>
    </generator>
    <id><?php echo $this->apiEndPoint ?>/tracking</id>

    <?php
    if (isset($this->items)):
        foreach ($this->items as $item): /* @var $item SE\Entity\TrackingItem */
    ?>

            <entry>
                <title><?php echo $item->getTerm() ?></title>
                <id><?php echo $this->apiEndPoint ?>/trackingitem/id/<?php echo $item->getId() ?></id>
                <updated><?php echo $item->getUpdated()->format('Y-m-d\TH:i:s\Z'); ?></updated>
                <app:edited><?php echo $item->getUpdated()->format('Y-m-d\TH:i:s\Z') ?></app:edited>
                <author>
                    <name>USER</name>
                </author>
                <content type="application/vnd.resbucks+xml">
                    <trackingitem>
                        <id><?php echo $item->getId() ?></id>
                        <requestdate><?php if($item->getRequestDate() instanceof DateTime) echo $item->getRequestDate()->format('Y-m-d\TH:i:s\Z') ?></requestdate>
                        <trackingdate><?php if($item->getTrackingDate() instanceof DateTime)  echo $item->getTrackingDate()->format('Y-m-d\TH:i:s\Z') ?></trackingdate>
                        <updateddate><?php if($item->getUpdated() instanceof DateTime)  echo $item->getUpdated()->format('Y-m-d\TH:i:s\Z') ?></updateddate>
                        <term><?php echo $item->getTerm() ?></term>
                    </trackingitem>
                </content>

        <?php
            if (!$item->isBeingFulFilled() && !$item->isTracked()):
        ?>
                <app:control>
                    <app:draft>yes</app:draft>
                </app:control>
        <?php
            endif;
        ?>

            <link rel="edit" href="<?php echo $this->apiEndPoint .'/tracking-fulfillment/id/'. $item->getId() ?>" />
            <link rel="self" href="<?php echo $this->apiEndPoint .'/tracking-fulfillment/id/'. $item->getId() ?>" />

            </entry>

    <?php
                endforeach;
            endif;
    ?>

</feed>


